################################
env_suite: robomimic
env_name: can

obs_dim: 9
cond_steps: 1
img_cond_steps: 1

action_dim: 7
horizon_steps: 4
act_steps: 4
################################
defaults:
  - _self_
hydra:
  run:
    dir: ${logdir}
_target_: agent.finetune.flowgrpo.train_flowgrpo_img_agent.TrainFlowGRPOImgAgent
name: ${env_name}_ft_flowgrpo_reflow_mlp_img_ta${horizon_steps}_td${flow_steps}_seed${seed}
logdir: ${oc.env:REINFLOW_LOG_DIR}/robomimic/finetune/${env_name}_ft_flowgrpo_reflow_mlp_img_ta${horizon_steps}_td${flow_steps}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}
base_policy_path: ${oc.env:REINFLOW_LOG_DIR}/robomimic/pretrain/can/ReFlow/state_2000.pt
robomimic_env_cfg_path: cfg/robomimic/env_meta/${env_name}-img.json
normalization_path: ${oc.env:REINFLOW_DATA_DIR}/robomimic/${env_name}-img/normalization.npz

seed: 42
device: cuda:0

#########################
# ODE integration steps (no denoising noise — pure flow)
flow_steps: 10
# Number of MC samples for CFM ratio per (step, env)
n_mc_samples: 4
#########################

env:
  n_envs: 50
  name: ${env_name}
  best_reward_threshold_for_success: 1
  max_episode_steps: 300
  save_video: false
  use_image_obs: true
  wrappers:
    robomimic_image:
      normalization_path: ${normalization_path}
      low_dim_keys: ['robot0_eef_pos',
                     'robot0_eef_quat',
                     'robot0_gripper_qpos']
      image_keys: ['robot0_eye_in_hand_image']
      shape_meta: ${shape_meta}
    multi_step:
      n_obs_steps: ${cond_steps}
      n_action_steps: ${act_steps}
      max_episode_steps: ${env.max_episode_steps}
      reset_within_step: true

shape_meta:
  obs:
    rgb:
      shape: [3, 96, 96]
    state:
      shape: [9]
  action:
    shape: [7]

wandb:
  entity: ${oc.env:REINFLOW_WANDB_ENTITY}
  project: robomimic-${env_name}-finetune
  run: ${now:%Y-%m-%d}_${now:%H-%M-%S}_${name}
  offline_mode: false

train:
  n_train_itr: 151
  n_steps: 300
  gamma: 0.999
  augment: true
  grad_accumulate: 15
  update_epochs: 1

  # FlowGRPO specific
  n_mc_samples: ${n_mc_samples}
  adv_clip: 5.0            # advantage clipping ±5 (per official FlowGRPO repo)
  target_kl: 1e-2          # KL early-stopping safety net
  batch_size: 500

  actor_lr: 2e-5
  actor_weight_decay: 0
  actor_lr_scheduler:
    type: cosine
    first_cycle_steps: 100
    warmup_steps: 10
    min_lr: 1e-5

  save_model_freq: 100
  val_freq: 10
  render:
    freq: 1
    num: 0

  reward_scale_running: true
  reward_scale_const: 1.0
  verbose: false

model:
  _target_: model.flow.ft_flowgrpo.flowgrpo_flow.FlowGRPOFlow
  device: ${device}
  actor_policy_path: ${base_policy_path}

  # VisionFlowMLP policy (same backbone as FPO++ / ReFlow PPO)
  policy:
    _target_: model.flow.mlp_flow.VisionFlowMLP
    backbone:
      _target_: model.common.vit.VitEncoder
      obs_shape: ${shape_meta.obs.rgb.shape}
      num_channel: ${eval:'3 * ${img_cond_steps}'}
      img_h: ${shape_meta.obs.rgb.shape[1]}
      img_w: ${shape_meta.obs.rgb.shape[2]}
      cfg:
        patch_size: 8
        depth: 1
        embed_dim: 128
        num_heads: 4
        embed_style: embed2
        embed_norm: 0
    augment: false          # augmentation handled in buffer
    spatial_emb: 128
    time_dim: 32
    mlp_dims: [512, 512, 512]
    residual_style: true
    img_cond_steps: ${img_cond_steps}
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    horizon_steps: ${horizon_steps}
    action_dim: ${action_dim}

  act_dim: ${action_dim}
  horizon_steps: ${horizon_steps}
  act_min: -1
  act_max: 1
  obs_dim: ${obs_dim}
  cond_steps: ${cond_steps}
  flow_steps: ${flow_steps}
  n_mc_samples: ${n_mc_samples}

  # FlowGRPO hyperparameters (per official repo)
  clip_ploss_coef: 1e-4     # tight trust region (vs PPO's 0.2, FPO++'s 0.01)
  adv_clip: 5.0             # advantage clipping magnitude
  cfm_diff_clamp: 5.0       # clamp on (l_old - l_new) before exp for stability
